import pandas as pd

# 1. DATA INITIALIZATION
df = pd.read_csv("AZA_MLE_Jul2018.csv", encoding='latin1')
df.columns = df.columns.str.strip()

# 2. TYPE CONVERSION
numeric_cols = ['Overall MLE', 'Male MLE', 'Female MLE', 'Overall CI - lower', 'Overall CI - upper', 'Overall Sample Size']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 3. TAXONOMIC FILTERING
target_classes = ["Mammalia", "Reptilia", "Aves"]
df = df[df['TaxonClass'].isin(target_classes)].copy()
df = df.dropna(subset=['Overall MLE'])

# 4. ADVANCED FEATURE ENGINEERING
df['Sex_Gap'] = df["Male MLE"] - df["Female MLE"]
df['CI_Breadth'] = df['Overall CI - upper'] - df['Overall CI - lower']
df['Reliability'] = df['Overall Sample Size'].apply(lambda x: 'High' if x > 100 else 'Low')

# Longevity Tiers
df['Longevity_Tier'] = pd.cut(df['Overall MLE'], 
                              bins=[0, 10, 20, 100], 
                              labels=['Short-Lived (<10y)', 'Medium-Lived (10-20y)', 'Long-Lived (>20y)'])

# Super Agers
class_avgs = df.groupby('TaxonClass')['Overall MLE'].transform('mean')
df['Super_Ager'] = df['Overall MLE'] > class_avgs

# 5. AGGREGATED SUMMARY TABLE
taxon_report = df.groupby('TaxonClass').agg(
    Avg_Lifespan=('Overall MLE', 'mean'),
    Max_Lifespan=('Overall MLE', 'max'),
    Species_Count=('Species Common Name', 'count'),
    Avg_Gender_Gap=('Sex_Gap', 'mean'),
    Mean_Uncertainty=('CI_Breadth', 'mean')
).round(2).sort_values(by='Avg_Lifespan', ascending=False)

# 6. REFINED REPORT GENERATION (report.txt)
with open('report.txt', 'w') as f:
    f.write("="*70 + "\n")
    f.write("       COMPREHENSIVE BIOLOGICAL LONGEVITY & CONSERVATION REPORT\n")
    f.write("="*70 + "\n\n")

    # PART 1: GLOBAL STATS
    f.write("[SECTION 1: TAXONOMIC CLASS OVERVIEW]\n")
    f.write("This table compares average lifespan and gender gaps across biological classes.\n")
    f.write(taxon_report.to_string() + "\n\n")

    # PART 2: THE OVERACHIEVERS
    f.write("[SECTION 2: THE SUPER-AGER TOP 10]\n")
    f.write("Species outperforming their biological class average by the highest margins.\n")
    top_10 = df.sort_values(by='Overall MLE', ascending=False).head(10)
    f.write(top_10[['Species Common Name', 'TaxonClass', 'Overall MLE', 'Reliability']].to_string(index=False) + "\n\n")

    # PART 3: GENDER ANALYSIS
    f.write("[SECTION 3: SEXUAL DIMORPHISM & GENDER GAP]\n")
    f.write("Top 3 species where Females significantly outlive Males:\n")
    female_lead = df.sort_values(by='Sex_Gap').head(3)
    f.write(female_lead[['Species Common Name', 'Sex_Gap']].to_string(index=False) + "\n\n")
    
    f.write("Top 3 species where Males significantly outlive Females:\n")
    male_lead = df.sort_values(by='Sex_Gap', ascending=False).head(3)
    f.write(male_lead[['Species Common Name', 'Sex_Gap']].to_string(index=False) + "\n\n")

    # PART 4: ECOLOGICAL TIERS
    f.write("[SECTION 4: LIFESPAN DISTRIBUTION TIERS]\n")
    tier_counts = df['Longevity_Tier'].value_counts()
    for tier, count in tier_counts.items():
        f.write(f"- {tier}: {count} species\n")
    f.write("\n")

    # PART 5: SCIENTIFIC INTEGRITY & RESEARCH GAPS
    f.write("[SECTION 5: DATA RELIABILITY & RESEARCH ADVISORY]\n")
    high_uncertainty = df.sort_values(by='CI_Breadth', ascending=False).head(3)
    f.write(f"Reliability Ratio: {len(df[df['Reliability']=='High'])} High / {len(df[df['Reliability']=='Low'])} Low\n")
    f.write("CRITICAL: The following species have the highest 'Uncertainty Window' and need further study:\n")
    f.write(high_uncertainty[['Species Common Name', 'CI_Breadth', 'Overall Sample Size']].to_string(index=False) + "\n")

    f.write("\n" + "="*70 + "\n")
    f.write("REPORT GENERATED BY PANDAS RESEARCH ENGINE | BIOLOGY DEPT\n")
    f.write("="*70 + "\n")

print(">>> SUCCESS: Refined research file 'report.txt' is ready.")